export const OrderType = {
    CREATED_AT: "CREATED_AT",
    COMMENT: "COMMENT",
    RATING: "RATING"
}

export const ProductType = {
    PRODUCT_TYPE_BOOK: "PRODUCT_TYPE_BOOK",
    PRODUCT_TYPE_CLOTHE: "PRODUCT_TYPE_CLOTHE",
    PRODUCT_TYPE_ELECTRONICS: "PRODUCT_TYPE_ELECTRONICS",
    PRODUCT_TYPE_FOOD: "PRODUCT_TYPE_FOOD",
    PRODUCT_TYPE_FURNITURE: "PRODUCT_TYPE_FURNITURE",
    PRODUCT_TYPE_LIFE: "PRODUCT_TYPE_LIFE",
    PRODUCT_TYPE_ALL: "PRODUCT_TYPE_ALL"
}

export const SortOrder = {
    ASCENDING: "ASCENDING",
    DESCENDING: "DESCENDING"
}